MA-22692-16 Add widevine HAL file to prevent trout build error
This patch fixed below build error:
$(file <out/file_name_tag.txt) was changed, regenerating...
[ 85% 276/324] build
out/target/product/trout_arm64/obj/PACKAGING/apex_sepolicy_tests_intermediates/vendor/apex/com.google.android.widevine.apex.pass
FAILED:
out/target/product/trout_arm64/obj/PACKAGING/apex_sepolicy_tests_intermediates/vendor/apex/com.google.android.widevine.apex.pass
/bin/bash -c "(rm -rf
out/target/product/trout_arm64/obj/PACKAGING/apex_sepolicy_tests_intermediates/vendor/apex/com.google.android.widevine.apex.pass
) && (mkdir -p ./ ) && (out/host/linux-x86/bin/apex_sepolicy_tests --all -f <(out/host/linux-x86/bin/deapexer --debugfs_path
out/host/linux-x86/bin/debugfs_static list -Z
out/target/product/trout_arm64/vendor/apex/com.google.android.widevine.apex)) && (touch
out/target/product/trout_arm64/obj/PACKAGING/apex_sepolicy_tests_intermediates/vendor/apex/com.google.android.widevine.apex.pass)"
Error: ./bin/hw/android.hardware.drm-service.widevine: tcontext(hal_drm_widevine_aidl_exec) is unknown

Change-Id: If7159a87b7c2ff56d2524d600e0acbd7635430e8
Signed-off-by: Haoran Wang <elven.wang@nxp.com>